name: scheduled
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - run: echo This job runs every 5 minutes
      - run: npm -v
      - run: node -v